---
title: antoniolee.me
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: antoniolee@outlook.com
description: Antonio Lee's personal website.
baseurl: "/"
url: http://antoniolee.me
markdown: kramdown
include:
- _pages
- assets
exclude:
- Gemfile
- Gemfile.lock
